meta:
    seed: 17

featurize:
    vectorize_sites:
        - method: 'tfidf'
          ngram_range: [1, 5]
          max_features: 50000
          sublinear_tf: True
          use_idf: True
    
    feature_types:
        prepared: []
        categorical: 
            - 'time_of_day'
        to_log: []
        to_scale_standard: 
            - 'session_timespan'
        to_scale_maxabs: 
            - 'day_of_week'
            - 'year_month'
            - 'month'

evaluate:
    show_weights: False
    submission:
        make: False
        name: 'yorko_fix_5feat_0drop_subtf'

compare:
    with: '7ec945f'