meta:
    seed: 17

featurize:
    vectorize_sites:
        - method: 'tfidf'
          ngram_range: [1, 5]
          max_features: 50000
    
    feature_types:
        prepared: []
        categorical:
            - 'time_of_day'
        to_log: []
        to_scale_standard: 
            - 'session_timespan'
        to_scale_maxabs: []

evaluate:
    show_weights: False
    submission:
        make: False
        name: 'yorko_nofix_2feat'

compare:
    with: 'baseline'